<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="SACHU-PC" ignored="0" name="RetryMultipleFailedTest" tests="9" failures="2" timestamp="03 Aug 2019 17:06:52 GMT" time="0.184" errors="0">
  <testcase name="testcase1" time="0.026" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.005" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase1" time="0.003" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.testcase1(MyTest.java:18)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase1 -->
  <testcase name="testcase2" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.002" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.003" classname="mytests.MyTest">
    <skipped/>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase2" time="0.023" classname="mytests.MyTest">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at mytests.MyTest.testcase2(MyTest.java:24)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- testcase2 -->
  <testcase name="testcase3" time="0.003" classname="mytests.MyTest"/>
</testsuite> <!-- RetryMultipleFailedTest -->
